---
title: "Getting started- our first analysis"
author: "Reproducible reseach clinic"
output:
  html_document:
    toc: false
---

<!-- The file analysis/chunks.R contains chunks that define default settings
shared across the workflowr files. -->
```{r read-chunk, include=FALSE, cache=FALSE}
knitr::read_chunk("chunks.R")
```

<!-- Update knitr chunk options -->
```{r knitr-opts-chunk, include=FALSE}
```

<!-- Insert the date the file was last updated -->
```{r last-updated, echo=FALSE, results='asis'}
```

<!-- Insert the code version (Git commit SHA1) if Git repository exists and R
 package git2r is installed -->
```{r code-version, echo=FALSE, results='asis'}
```
If you are just getting started, install the [R Programming language](https://www.r-project.org/) then download the integrated development environment (IDE) [RStudio](https://www.rstudio.com/). 
When you open RStudio, type the following into your `command window` or `console`:

```{r setup, include=TRUE, eval=FALSE}
install.packages("tidyverse")
install.packages("rmarkdown")
```

**Coming soon**


## Session information

<!-- Insert the session information into the document -->
```{r session-info}
```
