---
title: "Home"
author: "Reproducible reseach clinic"
output:
  html_document:
    toc: false
---

# Welcome to reproducible research clinic! 
The UC-Denver Reproducible Research Clinic seeks to inspire researchers to adopt the principles and practices of Reproducible Research (RR) so that they become part of daily scientific workflow. The club has two goals that will be addressed every meeting. We will: 

1. provide support and tutorials for the adoption and general use of RR tools 
2. help researchers with their specific statistical and coding needs in a "clinic" setting.


## Why should I try to learn reproducible research practices with R?

**TL;DR:** learning R and reproducible research practices makes your life _easier_. You spend less time copy-pasting and more time doing what matters. You don't need the whole langauge, we will show you the important parts!

See our [about page](about.html) for a longer description of why you should learn R for data analysis. 

## Programming for scientists

Getting started with a programming language can be intimidating, but it really shouldn't be! Keep in mind that most people in this group have been coding for **less than 3 years**! Learning to program as part of your academic work can make you more productive and is also an extremly lucrative skillset both inside and outside of academia (especially for languages like R and Python!). Most importantly, learning these tools empowers you to perform more reproducible research. More of your time will be spent reading and planning experiments while minimizing (eventually eliminating) the amount of copy-pasting and fumbling around with excel. Again, the best part is that R and python (we use R for the most part) are FREE and opensource languages! No license fees or proprietary formats required. 

## Need more reasons?
- [R makes beautiful charts](http://www.r-graph-gallery.com/portfolio/ggplot2-package/)
- [Can graphpad do this (p-values and stars)?](https://www.r-bloggers.com/add-p-values-and-significance-levels-to-ggplots/)
- [R was created by, and is used by professional statisticians](http://www.statisticsviews.com/details/feature/8585391/Created-by-statisticians-for-statisticians-How-R-took-the-world-of-statistics-by.html)
- The average salary for a data scientist (R and Python are the most popular languages) in the US is [$100,000](https://insights.stackoverflow.com/survey/2017#work-salaries-by-geography)
- It isn't that hard to get started!

## How will I learn R for my analysis?
Most people go about learning a language by trying to read through a whole introduction and doing all the boring exercises first. It may be months before they get to do anything intersting, relevant, or useful. We dont think that is a useful exercise or even the most efficient way to learn. As scientists, we learn to solve problems and get answers. We find the papers and learn what we have to in order to do the experiments and solve problems. We aren't computer scientists, so let's take the same approach to learning R!
We will learn by exploring YOUR data. We show you the relevant commands, and you learn how to tweak options and explore even more. You learn what you need and want, that's it!



# Our first analysis (a quick intro to data analysis with R)

In a coming post, we will perform our first quick analysis on some simulated data and learn the basics of the language as we go. If you have trouble, don't hesitate to contact us or stop by a meeting, we are happy to help!