---
title: "Organizers and Contact Information"
output:
  html_document:
    toc: false
---

## *Network organizers*

### Nicholas George

Graduate Student  
nicholas.m.george@ucdenver.edu  
Anschutz Campus - Sch of Med - Neuroscience Program, Cell and Developmental Bio

### Joshua Johnson

Assistant Professor  
Division of Reproductive Sciences  
Department of Obstetrics and Gynecology  
University of Colorado Denver (AMC)  
Building RC2, Room P15 3103  
Mail Stop 8613  
Aurora, Colorado 80045  
Office: 303.724.7281  
Mobile: 203.889.8123  
joshua.2.johnson@ucdenver.edu  

### Wladimir Labeikovski

Health Sciences Library  
UC Denver | Anschutz Medical Campus  
orcid.org/0000-0001-6074-3269  

### Tzu Phang
Tzu.Phang@ucdenver.edu  
Research II : room 9400 D  
Anschutz Campus - Sch of Med - BIOMED  

## *Branches*

*If you feel like reproducible research practices helped streamline and improve your workflow, please consider starting one in your own department! Let one of our Network organizers know if you are interested and we will help you get organized and get started!*  

## RRN- Reproductive sciences
**Organizer:** Joshua Johnson, PhD  
**Meeting Time:** 11am, first and third Friday of the month  
**Meeting Location:** RC2, 3rd Floor 3109  
**Contact:**
Assistant Professor  
Division of Reproductive Sciences  
Department of Obstetrics and Gynecology  
University of Colorado Denver (AMC)  
Building RC2, Room P15 3103  
Mail Stop 8613  
Aurora, Colorado 80045  
Office: 303.724.7281  
Mobile: 203.889.8123  
joshua.2.johnson@ucdenver.edu  


## More coming soon!